'use client'

import { useState } from "react";
import { Roboto } from "next/font/google";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import { ClerkProvider } from '@clerk/nextjs'
import {CartContext} from './_context/CartContext'
import "./globals.css";

const inter = Roboto({ subsets: ["latin"],weight:"700" });

// export const metadata = {
//   title: "MyStore",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  const [cart,setCart] = useState([]);
  return (
    <ClerkProvider>
      <CartContext.Provider value={{cart,setCart}}>
      <html lang="en">
        <body className={inter.className} suppressHydrationWarning={true}>
          <Header />
          {children}
          <Footer />
        </body>
      </html>
      </CartContext.Provider>
    </ClerkProvider>
  );
}
